import { readFileSync, existsSync } from "fs";
import { join } from "path";

// Embedded MCP tools - these replace the external Python MCP server
export interface McpToolDef {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}

// Load agent instructions from the embedded file
function loadAgentInstructions(): string {
  const instructionsPath = join(process.cwd(), "public", "agent-instructions.md");
  try {
    if (existsSync(instructionsPath)) {
      return readFileSync(instructionsPath, "utf-8");
    }
  } catch (err) {
    console.warn("Could not load agent instructions:", err);
  }
  
  // Fallback instructions
  return `# Symbols / DOMQL v3 — AI Agent Instructions

You are working inside a **Symbols/DOMQL v3** project. These rules are absolute and override any general coding instincts.

## 1. Components are OBJECTS — never functions
export const Header = { extends: 'Flex', padding: 'A' }  // CORRECT
export const Header = (el, state) => ({ padding: 'A' })  // WRONG

## 2. NO imports between project files — EVER
Components reference each other by PascalCase key name in the tree. No import statements between components/, pages/, functions/, etc.

## 3. Pages use 'Flex' with flow: 'column' — NOT 'Page'
export const main = { extends: 'Flex', flow: 'column', minHeight: '100vh', ... }  // CORRECT
export const main = { extends: 'Page', ... }  // WRONG — causes black screen

## 4. For images, NEVER use extends: 'Img' or extends: 'Image'
CORRECT: { extends: 'Flex', tag: 'img', src: '...', width: '100px' }
WRONG: { extends: 'Img', src: '...' }

## 5. pages/index.js — imports ARE allowed here (it's the registry)
import { main } from './main.js'
export default { '/': main }

## 6. Use flexAlign not align for Flex shorthand
{ extends: 'Flex', flexAlign: 'center center' }  // CORRECT
{ extends: 'Flex', align: 'center center' }       // WRONG

## 7. State — use s.update(), never mutate directly
onClick: (e, el, s) => s.update({ count: s.count + 1 })  // CORRECT
onClick: (e, el, s) => { s.count = s.count + 1 }          // WRONG

## 8. All folders are flat — no subfolders
components/Navbar.js       ✅
components/nav/Navbar.js   ❌

## 9. Always generate complete file contents, never partial snippets
Include all required project structure files based on the reference project.

## 10. main.js MUST use actual project components, NOT generic placeholders
CORRECT: Reference all major components you generated by their PascalCase key names
WRONG: Generic "Symbols App" or "Add your content here" placeholder content`;
}

// Get all available MCP tools
export function getAvailableMcpTools(): McpToolDef[] {
  return [
    {
      name: "get_project_rules",
      description: "Get the Symbols/DOMQL v3 framework rules and best practices",
      inputSchema: {
        type: "object",
        properties: {},
        required: [],
      },
    },
    {
      name: "search_symbols_docs",
      description: "Search the Symbols documentation knowledge base",
      inputSchema: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description: "Natural language search query",
          },
          max_results: {
            type: "number",
            description: "Maximum number of results (1-5)",
            default: 3,
          },
        },
        required: ["query"],
      },
    },
  ];
}

// Call an MCP tool
export async function callEmbeddedMcpTool(
  toolName: string,
  toolInput: Record<string, unknown>
): Promise<string> {
  if (toolName === "get_project_rules") {
    return loadAgentInstructions();
  }

  if (toolName === "search_symbols_docs") {
    const query = String(toolInput.query || "").toLowerCase();
    const instructions = loadAgentInstructions();
    
    // Simple search - find sections matching the query
    const lines = instructions.split("\n");
    const results: string[] = [];
    
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].toLowerCase().includes(query)) {
        // Include context around the match
        const start = Math.max(0, i - 1);
        const end = Math.min(lines.length, i + 3);
        const context = lines.slice(start, end).join("\n");
        if (!results.includes(context)) {
          results.push(context);
        }
      }
    }
    
    return results.length > 0 
      ? results.join("\n\n---\n\n")
      : `No results found for "${query}". Please refer to the project rules.`;
  }

  throw new Error(`Unknown MCP tool: ${toolName}`);
}
