import { NextRequest } from "next/server";
import { callMcpTool, listMcpTools } from "@/lib/mcp-client";
import { streamChat, OpenRouterMessage, McpToolDef } from "@/lib/openrouter";
import { parseGeneratedFiles, writeGeneratedFiles, readProjectFiles } from "@/lib/file-writer";
import { getSymbolsContext } from "@/lib/symbols-context";
import { saveContext, loadContext, getContextSummary, clearContext, AgentContext } from "@/lib/agent-context";

// Force Node.js runtime
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SYSTEM_PROMPT = `You are Symbols AI — an expert assistant for building projects with the Symbols/DOMQL v3 framework.

Your job is to help users create and EDIT Symbols projects. You have access to:
1. A reference Symbols project in the symbols/ folder (provided in context)
2. MCP tools that provide framework documentation, rules, and references
3. The user's CURRENT PROJECT files (if they have an active project)

CRITICAL: EDITING vs CREATING
- If the user has an ACTIVE PROJECT (shown in context), they want to EDIT that project, not create a new one
- For edit requests like "fix the navbar", "add a cart modal", "change the colors" — ONLY output the specific files that need changes
- Do NOT regenerate the entire project for small fixes
- Reference the existing project files to understand the current structure before making changes

CRITICAL WORKFLOW - MANDATORY VERIFICATION:
1. BEFORE making ANY changes, you MUST call get_project_rules to verify Symbols v3 rules
2. NEVER assume you know the correct pattern - ALWAYS verify against MCP documentation first
3. If fixing bugs, use search_symbols_docs to find the correct pattern before implementing
4. ALWAYS reference the symbols/ folder structure as your primary guide for project organization
5. Follow the exact file structure, naming conventions, and patterns from the reference project
6. Generate code that strictly follows v3 syntax — violations cause silent failures

⚠️ FORBIDDEN PATTERNS (These cause black screens or silent failures):
- NEVER use extends: 'Page' in main.js → Use extends: 'Flex' with flow: 'column'
- NEVER use imperative DOM manipulation (document.getElementById, el.style.display)
- NEVER use el.call() for custom functions → Use reactive patterns only
- NEVER invent fake rules or patterns → Verify with MCP first
- NEVER assume reactive display: (el, s) => ... is a bug - it's CORRECT
- NEVER leave smbls/pages/index.js as 'export default {}' → Must import and export pages
- NEVER leave smbls/designSystem/index.js as 'export default {}' → Must import all design tokens
- NEVER leave smbls/index.js without state and config exports

REFERENCE PROJECT USAGE:
- Use the symbols/index.js pattern for imports and create() setup
- Follow the symbols/config.js structure for configuration
- Mirror the folder structure: components/, pages/, functions/, designSystem/, etc.
- Match the export patterns in each directory's index.js
- Apply the same coding style and conventions

When generating or editing project files, you MUST format each file exactly as follows:

**smbls/path/to/FileName.js**
\`\`\`js
export const FileName = {
  extends: 'Flex',
  // ... content
}
\`\`\`

Or use this inline comment format:
\`\`\`js // smbls/path/to/FileName.js
export const FileName = {
  extends: 'Flex',
  // ... content
}
\`\`\`

CRITICAL RULES:
- Use **double asterisks** around the filename path
- Follow immediately with a code block
- Use named exports: export const Name = { }
- Pages use dash-case filenames with camelCase exports (e.g., export const dashboard = { })
- Generate ALL required files for a complete working project
- Never use default exports for components or pages
- In pages, reference components by PascalCase KEY name (NOT extends: 'ComponentName')
  CORRECT: Navbar: { }
  WRONG: Header: { extends: 'Navbar' }
- Components auto-extend when key matches component name
- Use only design system colors that exist in designSystem/color.js

⚠️ CRITICAL - pages/main.js MUST:
1. Be generated with actual project components (Sidebar, Navbar, ProductGrid, etc.)
2. NEVER use generic placeholder content like "Symbols App" or "Add your content here"
3. Reference all major components you generated by their PascalCase key names
4. Use extends: 'Flex' with flow: 'column' or 'row', NOT extends: 'Page'

⚠️ CRITICAL - For images, NEVER use extends: 'Img' or extends: 'Image':
- CORRECT: { extends: 'Flex', tag: 'img', src: '...', width: '100px' }
- WRONG: { extends: 'Img', src: '...' }

Always generate complete file contents, never partial snippets. Include all required project structure files based on the reference project.`;

export async function POST(req: NextRequest) {
  const { messages, model, autoMcp, goal, task, projectName: customProjectName, activeProject } = await req.json();
  const apiProvider = req.headers.get("x-api-provider") as "openrouter" | "claude" | null;
  const apiKey = req.headers.get("x-api-key") ?? 
    (apiProvider === "claude" ? process.env.CLAUDE_API_KEY : process.env.OPENROUTER_API_KEY);

  // Load previous context
  const contextSummary = await getContextSummary();
  const existingContext = await loadContext();

  if (!apiKey) {
    const providerName = apiProvider === "claude" ? "Claude" : "OpenRouter";
    return new Response(
      JSON.stringify({ error: `${providerName} API key is required. Set ${apiProvider === "claude" ? "CLAUDE_API_KEY" : "OPENROUTER_API_KEY"} or pass x-api-key header.` }),
      { status: 401, headers: { "Content-Type": "application/json" } }
    );
  }

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      const send = (data: Record<string, unknown>) => {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      };

      try {
        // Load MCP tools
        let mcpTools: McpToolDef[] = [];
        if (autoMcp) {
          try {
            mcpTools = await listMcpTools();
            send({ type: "status", content: `Loaded ${mcpTools.length} MCP tools` });
          } catch (err) {
            send({ type: "status", content: `MCP connection warning: ${err instanceof Error ? err.message : err}` });
          }
        }

        // Build conversation
        const systemContent = contextSummary 
          ? `${SYSTEM_PROMPT}\n\n${contextSummary}`
          : SYSTEM_PROMPT;
        
        const conversation: OpenRouterMessage[] = [
          { role: "system", content: systemContent },
          ...messages.map((m: { role: string; content: string }) => ({
            role: m.role as "user" | "assistant",
            content: m.content,
          })),
        ];

        // Auto-inject project rules for first message or project generation requests
        const lastMsg = messages[messages.length - 1]?.content?.toLowerCase() ?? "";
        const needsRules =
          messages.length <= 1 ||
          lastMsg.includes("create") ||
          lastMsg.includes("generate") ||
          lastMsg.includes("build") ||
          lastMsg.includes("project") ||
          lastMsg.includes("component") ||
          lastMsg.includes("page");

        if (autoMcp && needsRules) {
          // ALWAYS inject the reference symbols folder first
          try {
            send({ type: "status", content: "Loading reference Symbols project..." });
            const symbolsContext = await getSymbolsContext();
            conversation.splice(1, 0, {
              role: "system",
              content: symbolsContext,
            });
          } catch (err) {
            send({ type: "status", content: `Could not load symbols folder: ${err instanceof Error ? err.message : err}` });
          }

          // Then inject MCP framework rules
          try {
            send({ type: "tool_call", name: "get_project_rules", status: "calling" });
            const rules = await callMcpTool("get_project_rules");
            send({ type: "tool_result", name: "get_project_rules", status: "done" });
            conversation.splice(2, 0, {
              role: "system",
              content: `[SYMBOLS FRAMEWORK RULES — MUST FOLLOW]\n${rules}`,
            });
          } catch (err) {
            send({ type: "status", content: `Could not load rules: ${err instanceof Error ? err.message : err}` });
          }
        }

        // Inject active project context if user has a project they're working on
        if (activeProject) {
          try {
            send({ type: "status", content: `Loading active project: ${activeProject}...` });
            const projectFiles = await readProjectFiles(activeProject);
            if (projectFiles.length > 0) {
              const projectContext = projectFiles.map(f => 
                `**${f.path}**\n\`\`\`js\n${f.content}\n\`\`\``
              ).join("\n\n");
              
              conversation.splice(1, 0, {
                role: "system",
                content: `[ACTIVE PROJECT: ${activeProject}]
The user is currently working on this project. For edit requests, ONLY modify the specific files that need changes.
Do NOT regenerate the entire project unless explicitly asked.

CURRENT PROJECT FILES:
${projectContext}`,
              });
              send({ type: "status", content: `Loaded ${projectFiles.length} files from ${activeProject}` });
            }
          } catch (err) {
            send({ type: "status", content: `Could not load project files: ${err instanceof Error ? err.message : err}` });
          }
        }

        // Stream the AI response
        let fullResponse = "";
        let toolCallBuffer: {
          id: string;
          name: string;
          arguments: string;
        } | null = null;

        const maxToolRounds = 5;
        let toolRound = 0;

        async function runStream(conv: OpenRouterMessage[]) {
          toolCallBuffer = null;
          const isClaude = apiProvider === "claude";

          for await (const chunk of streamChat(conv, model, apiKey!, mcpTools, apiProvider || "openrouter")) {
            try {
              const parsed = JSON.parse(chunk);
              
              if (isClaude) {
                // Claude API response format
                const eventType = parsed.type;
                
                if (eventType === "content_block_delta") {
                  const delta = parsed.delta;
                  if (delta?.type === "text_delta" && delta?.text) {
                    fullResponse += delta.text;
                    send({ type: "text", content: delta.text });
                  } else if (delta?.type === "input_json_delta" && delta?.partial_json) {
                    // Tool call arguments streaming
                    if (toolCallBuffer) {
                      toolCallBuffer.arguments += delta.partial_json;
                    }
                  }
                } else if (eventType === "content_block_start") {
                  const contentBlock = parsed.content_block;
                  if (contentBlock?.type === "tool_use") {
                    // New tool call starting
                    if (toolCallBuffer && toolCallBuffer.name) {
                      await processToolCall(conv, toolCallBuffer);
                    }
                    toolCallBuffer = {
                      id: contentBlock.id,
                      name: contentBlock.name,
                      arguments: "",
                    };
                  }
                } else if (eventType === "message_delta") {
                  const stopReason = parsed.delta?.stop_reason;
                  if (stopReason === "tool_use" && toolCallBuffer) {
                    await processToolCall(conv, toolCallBuffer);
                    toolCallBuffer = null;

                    if (toolRound < maxToolRounds) {
                      toolRound++;
                      await runStream(conv);
                      return;
                    }
                  }
                }
              } else {
                // OpenRouter/OpenAI response format
                const delta = parsed.choices?.[0]?.delta;
                const finishReason = parsed.choices?.[0]?.finish_reason;

                if (delta?.content) {
                  fullResponse += delta.content;
                  send({ type: "text", content: delta.content });
                }

                // Handle tool calls
                if (delta?.tool_calls) {
                  for (const tc of delta.tool_calls) {
                    if (tc.id) {
                      // New tool call
                      if (toolCallBuffer && toolCallBuffer.name) {
                        // Process previous buffered tool call
                        await processToolCall(conv, toolCallBuffer);
                      }
                      toolCallBuffer = {
                        id: tc.id,
                        name: tc.function?.name ?? "",
                        arguments: tc.function?.arguments ?? "",
                      };
                    } else if (toolCallBuffer) {
                      // Continue accumulating arguments
                      if (tc.function?.name) toolCallBuffer.name += tc.function.name;
                      if (tc.function?.arguments) toolCallBuffer.arguments += tc.function.arguments;
                    }
                  }
                }

                if (finishReason === "tool_calls" && toolCallBuffer) {
                  await processToolCall(conv, toolCallBuffer);
                  toolCallBuffer = null;

                  // Continue the conversation with tool results
                  if (toolRound < maxToolRounds) {
                    toolRound++;
                    await runStream(conv);
                    return;
                  }
                }
              }
            } catch {
              // Non-JSON chunk, skip
            }
          }
        }

        async function processToolCall(
          conv: OpenRouterMessage[],
          tc: { id: string; name: string; arguments: string }
        ) {
          send({ type: "tool_call", name: tc.name, status: "calling" });

          let args: Record<string, unknown> = {};
          try {
            args = JSON.parse(tc.arguments);
          } catch {
            // Empty args
          }

          let result: string;
          try {
            result = await callMcpTool(tc.name, args);
          } catch (err) {
            result = `Error: ${err instanceof Error ? err.message : err}`;
          }

          send({ type: "tool_result", name: tc.name, status: "done", preview: result.slice(0, 200) });

          // Add assistant tool_calls message and tool result to conversation
          // Claude uses a different format than OpenRouter
          if (apiProvider === "claude") {
            // Claude format: assistant message with tool_use content block
            conv.push({
              role: "assistant",
              content: [
                {
                  type: "tool_use",
                  id: tc.id,
                  name: tc.name,
                  input: JSON.parse(tc.arguments || "{}"),
                }
              ] as unknown as string,
            });
            // Claude format: user message with tool_result content block
            conv.push({
              role: "user",
              content: [
                {
                  type: "tool_result",
                  tool_use_id: tc.id,
                  content: result,
                }
              ] as unknown as string,
            });
          } else {
            // OpenRouter/OpenAI format
            conv.push({
              role: "assistant",
              content: "",
              tool_calls: [
                {
                  id: tc.id,
                  type: "function",
                  function: { name: tc.name, arguments: tc.arguments },
                },
              ],
            });
            conv.push({
              role: "tool",
              content: result,
              tool_call_id: tc.id,
            });
          }

          // Parse files from tool result and write them immediately
          if (tc.name === "generate_project" || tc.name === "generate_page" || tc.name === "generate_component") {
            const toolFiles = parseGeneratedFiles(result);
            console.log(`[chat] Tool ${tc.name} parsed files:`, toolFiles.length);
            if (toolFiles.length > 0) {
              const projectName = `symbols-project-${Date.now()}`;
              const written = await writeGeneratedFiles(toolFiles, projectName);
              send({ type: "files", projectName, files: written });
            }
          }
        }

        await runStream(conversation);

        // Parse and save generated files
        const files = parseGeneratedFiles(fullResponse);
        console.log(`[chat] fullResponse length: ${fullResponse.length}, parsed files: ${files.length}`);
        if (files.length === 0 && fullResponse.length > 0) {
          // Log a snippet to help debug pattern matching
          console.log(`[chat] first 500 chars of response:`, fullResponse.substring(0, 500));
        }
        
        // Save context for future sessions
        const currentTask = task || existingContext.currentTask || messages[messages.length - 1]?.content?.substring(0, 100);
        await saveContext({
          goal: goal || existingContext.goal,
          currentTask: currentTask,
          lastUpdated: new Date().toISOString(),
          activeFiles: files.length > 0 ? files.map(f => f.path) : existingContext.activeFiles,
        });
        
        if (files.length > 0) {
          // Priority: activeProject > customProjectName > timestamp-based name
          // This ensures edits go to the same folder instead of creating new ones
          let finalProjectName: string;
          
          if (activeProject) {
            // User is editing an existing project - reuse the same folder
            finalProjectName = activeProject;
          } else if (customProjectName) {
            // User specified a custom name (from template or conversion)
            finalProjectName = customProjectName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
          } else {
            // Fallback: create new timestamped project
            finalProjectName = `symbols-project-${Date.now()}`;
          }
          
          // Try to write files to disk (may fail on read-only filesystems like Railway)
          const written = await writeGeneratedFiles(files, finalProjectName);
          
          // Send full file contents to client so it can handle storage
          send({ 
            type: "files", 
            projectName: finalProjectName, 
            files: written,
            fileContents: files // Include full file contents for client-side storage
          });
        }

        send({ type: "done" });
      } catch (err) {
        send({
          type: "error",
          content: err instanceof Error ? err.message : "Unknown error",
        });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}

// Context management endpoints
export async function PUT(req: NextRequest) {
  try {
    const body = await req.json();
    await saveContext(body);
    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Failed to save context" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}

export async function GET() {
  try {
    const context = await loadContext();
    return new Response(JSON.stringify(context), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Failed to load context" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}

export async function DELETE() {
  try {
    await clearContext();
    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Failed to clear context" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
